production:
  server: "https://faye-gambit.herokuapp.com/faye"

#this is the address of this heroku app once youâ€™ve deployed it, plus the `/faye` extension.

  secret_token: "94a23d511dc3828940af7decb285db9873b13c2c36a59d5e9bbdcd1b39115833"
  signature_expiration: 3600 # one day
